# Generated by Django 2.2.4 on 2019-08-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128, unique=True, verbose_name='昵称')),
                ('intro_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='个人链接')),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('blog_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='博客链接')),
                ('weibo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='微博链接')),
                ('github_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub 链接')),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='标签名')),
                ('color', models.IntegerField(verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'index_together': {('color',)},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='文章标题')),
                ('origin_title', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='原文标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=128, verbose_name='作者')),
                ('html_url', models.URLField(blank=True, max_length=128, null=True, verbose_name='原文链接')),
                ('github_url', models.URLField(blank=True, max_length=128, null=True, verbose_name='GitHub 链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='译文发布时间')),
                ('origin_at', models.DateTimeField(auto_now=True, verbose_name='原文创建时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category', verbose_name='分类')),
                ('drafters', models.ManyToManyField(related_name='drafters', to='app.User', verbose_name='定稿人')),
                ('proofreaders', models.ManyToManyField(related_name='proofreaders', to='app.User', verbose_name='校对者')),
                ('tag', models.ManyToManyField(related_name='tags', to='app.Tag', verbose_name='标签')),
                ('translators', models.ManyToManyField(related_name='translators', to='app.User', verbose_name='译者')),
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
                'unique_together': {('title', 'author')},
                'index_together': {('title',)},
            },
        ),
    ]
