# Generated by Django 2.2.4 on 2019-08-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(verbose_name='译文发布时间'),
        ),
    ]
