# Generated by Django 2.2.4 on 2019-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190824_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preface',
            field=models.TextField(blank=True, null=True, verbose_name='前言'),
        ),
    ]
