# Generated by Django 2.2.4 on 2019-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_preface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='商品名')),
                ('current_price', models.IntegerField(verbose_name='现价')),
                ('origin_price', models.IntegerField(verbose_name='原价')),
                ('banner_display', models.BooleanField(verbose_name='是否展示在 banner 位')),
                ('preface', models.CharField(max_length=256, verbose_name='简介')),
                ('body', models.TextField(verbose_name='内容')),
                ('thumbnail_url', models.URLField(max_length=128, verbose_name='缩略图链接')),
                ('purchase_url', models.URLField(max_length=128, verbose_name='购买链接')),
            ],
        ),
    ]
