# Generated by Django 2.2.5 on 2019-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='商品是否有效'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='商品是否已发布'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='商品来源'),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='商品无效原因'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preface',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='简介'),
        ),
    ]
