# Generated by Django 2.2.5 on 2019-09-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190913_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('name',)},
        ),
    ]
